// <auto-generated />
using System;
using Antigaspi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Antigaspi.Infrastructure.Migrations
{
    [DbContext(typeof(AntigaspiDbContext))]
    [Migration("20260203144110_AddCitiesTable")]
    partial class AddCitiesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Antigaspi.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            NameAr = "أكادير",
                            NameEn = "Agadir",
                            NameFr = "Agadir"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            NameAr = "الحسيمة",
                            NameEn = "Al Hoceima",
                            NameFr = "Al Hoceima"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            NameAr = "بني ملال",
                            NameEn = "Beni Mellal",
                            NameFr = "Beni Mellal"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            NameAr = "برشيد",
                            NameEn = "Berrechid",
                            NameFr = "Berrechid"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            NameAr = "الدار البيضاء",
                            NameEn = "Casablanca",
                            NameFr = "Casablanca"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            NameAr = "الداخلة",
                            NameEn = "Dakhla",
                            NameFr = "Dakhla"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            NameAr = "الجديدة",
                            NameEn = "El Jadida",
                            NameFr = "El Jadida"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            NameAr = "الراشيدية",
                            NameEn = "Errachidia",
                            NameFr = "Errachidia"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            NameAr = "الصويرة",
                            NameEn = "Essaouira",
                            NameFr = "Essaouira"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            NameAr = "فاس",
                            NameEn = "Fes",
                            NameFr = "Fès"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            NameAr = "كلميم",
                            NameEn = "Guelmim",
                            NameFr = "Guelmim"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            NameAr = "إفران",
                            NameEn = "Ifrane",
                            NameFr = "Ifrane"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            NameAr = "القنيطرة",
                            NameEn = "Kenitra",
                            NameFr = "Kénitra"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            NameAr = "الخميسات",
                            NameEn = "Khemisset",
                            NameFr = "Khémisset"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            NameAr = "خنيفرة",
                            NameEn = "Khenifra",
                            NameFr = "Khénifra"
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            NameAr = "خريبكة",
                            NameEn = "Khouribga",
                            NameFr = "Khouribga"
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            NameAr = "العيون",
                            NameEn = "Laayoune",
                            NameFr = "Laâyoune"
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            NameAr = "العرائش",
                            NameEn = "Larache",
                            NameFr = "Larache"
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            NameAr = "مراكش",
                            NameEn = "Marrakech",
                            NameFr = "Marrakech"
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            NameAr = "مكناس",
                            NameEn = "Meknes",
                            NameFr = "Meknès"
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            NameAr = "المحمدية",
                            NameEn = "Mohammedia",
                            NameFr = "Mohammedia"
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            NameAr = "الناظور",
                            NameEn = "Nador",
                            NameFr = "Nador"
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            NameAr = "ورزازات",
                            NameEn = "Ouarzazate",
                            NameFr = "Ouarzazate"
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            NameAr = "وجدة",
                            NameEn = "Oujda",
                            NameFr = "Oujda"
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            NameAr = "الرباط",
                            NameEn = "Rabat",
                            NameFr = "Rabat"
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            NameAr = "آسفي",
                            NameEn = "Safi",
                            NameFr = "Safi"
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            NameAr = "سلا",
                            NameEn = "Sale",
                            NameFr = "Salé"
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            NameAr = "سطات",
                            NameEn = "Settat",
                            NameFr = "Settat"
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            NameAr = "سيدي قاسم",
                            NameEn = "Sidi Kacem",
                            NameFr = "Sidi Kacem"
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            NameAr = "سيدي سليمان",
                            NameEn = "Sidi Slimane",
                            NameFr = "Sidi Slimane"
                        },
                        new
                        {
                            Id = 31,
                            IsActive = true,
                            NameAr = "طنجة",
                            NameEn = "Tangier",
                            NameFr = "Tanger"
                        },
                        new
                        {
                            Id = 32,
                            IsActive = true,
                            NameAr = "طانطان",
                            NameEn = "Tan-Tan",
                            NameFr = "Tan-Tan"
                        },
                        new
                        {
                            Id = 33,
                            IsActive = true,
                            NameAr = "تاونات",
                            NameEn = "Taounate",
                            NameFr = "Taounate"
                        },
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            NameAr = "تارودانت",
                            NameEn = "Taroudant",
                            NameFr = "Taroudant"
                        },
                        new
                        {
                            Id = 35,
                            IsActive = true,
                            NameAr = "تازة",
                            NameEn = "Taza",
                            NameFr = "Taza"
                        },
                        new
                        {
                            Id = 36,
                            IsActive = true,
                            NameAr = "تمارة",
                            NameEn = "Temara",
                            NameFr = "Témara"
                        },
                        new
                        {
                            Id = 37,
                            IsActive = true,
                            NameAr = "تطوان",
                            NameEn = "Tetouan",
                            NameFr = "Tétouan"
                        },
                        new
                        {
                            Id = 38,
                            IsActive = true,
                            NameAr = "تيزنيت",
                            NameEn = "Tiznit",
                            NameFr = "Tiznit"
                        });
                });

            modelBuilder.Entity("Antigaspi.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Antigaspi.Domain.Entities.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Antigaspi.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastVerificationEmailSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("OtpExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("VerificationEmailCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Antigaspi.Domain.Entities.Offer", b =>
                {
                    b.HasOne("Antigaspi.Domain.Entities.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Antigaspi.Domain.ValueObjects.Money", "OriginalPrice", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("OriginalPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("OriginalPriceCurrency");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("Antigaspi.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsMany("Antigaspi.Domain.Entities.OfferStatusEntry", "StatusHistory", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("ChangedAt")
                                .HasColumnType("datetime2");

                            b1.Property<Guid?>("ChangedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reason")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.HasKey("OfferId", "Id");

                            b1.ToTable("OfferStatusHistory", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.Navigation("OriginalPrice")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Seller");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Antigaspi.Domain.Entities.Seller", b =>
                {
                    b.HasOne("Antigaspi.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Antigaspi.Domain.Entities.Seller", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Antigaspi.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("SellerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Longitude");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ZipCode");

                            b1.HasKey("SellerId");

                            b1.ToTable("Sellers");

                            b1.WithOwner()
                                .HasForeignKey("SellerId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
